version: '3.8'
services:
  node:
    build: .
    image: node
    container_name: node
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true